-
  image: Visual Studio 2017

# configuration for "master" branch
# build in Release mode and deploy to Nuget
-
  branches:
    only:
      - master
  configuration: Release
  nuget:
    disable_publish_on_pr: true
  install:
    - ps: .\tools\Appveyor\install_dotnet_devpack.ps1
  before_build:
    - dotnet restore .\Routine.sln
  build_script:
    - dotnet build .\Routine.sln
  test:
    assemblies:
      only:
        - Routine.Test.dll
  after_test:
    - ps: .\src\Routine\Scripts\BuildNugetPackage.ps1

  deploy:
    # The following is the details allowing for appveyor to push the 
    # new version of the package to nuget.org.
  - provider: NuGet
    name: production
    api_key: 
      secure: 0uEiB3xE0Pxwlk20sxtf+Vy9WZQrbA2XYIbZbvQZficGLgJ7u8Cvcfu/t2T/rlmq
    on:
      branch: master
      APPVEYOR_REPO_TAG: true
  artifacts:
  - path: .\artifacts\**\*.nupkg
    name: Nuget
# configuration for "develop" branch
# build in Release mode and create Nuget pack
-
  branches:
    only:
      - develop
  configuration: Release
  nuget:
    disable_publish_on_pr: true
  install:
    - ps: .\tools\Appveyor\install_dotnet_devpack.ps1
  before_build:
    - dotnet restore .\Routine.sln
  build_script:
    - dotnet build .\Routine.sln
  test:
    assemblies:
      only:
        - Routine.Test.dll

# configuration for all other branches except "master" and "develop"
# build in Debug mode and deploy locally for testing
-
  branches:
    except:
      - master
      - develop
  configuration: Release
  install:
    - ps: .\tools\Appveyor\install_dotnet_devpack.ps1
  before_build:
    - dotnet restore .\Routine.sln
    - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory tools
    - choco install opencover.portable
    - choco install codecov
  build_script:
    - dotnet build .\Routine.sln
  test_script:
    - OpenCover.Console.exe -register:user -target:.\tools\NUnit.Runners.2.6.4\tools\nunit-console.exe -targetargs:".\test\Routine.Test\bin\Release\net48\Routine.Test.dll -noshadow" -filter:"+[Routine*]*" -output:".\routine_coverage.xml"
    - codecov -f "routine_coverage.xml"
  #test:
  #  assemblies:
  #    only:
  #      - Routine.Test.dll
  after_test:
    - ps: .\src\Routine\Scripts\BuildNugetPackage.ps1

  deploy:
    # The following is the details allowing for appveyor to push the 
    # new version of the package to nuget.org.
  - provider: NuGet
    server: https://www.myget.org/F/routine/api/v2/package
    name: production
    api_key: 
      secure: PmfkNawJ/K1FWOqIMcDCC8bPHOQ4++o+5TmARFSqLUi8bX1PbNRNN2PDrsJ0t81g
  artifacts:
  - path: .\artifacts\**\*.nupkg
    name: Nuget