name: .NET

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
      - name: Code Coverage Summary Report
        uses: 5monkeys/cobertura-action@master
        with:
          path: ${{ github.workspace }}/test/Routine.Test.Performance/coverage.cobertura.xml
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          skip_covered : false
          only_changed_files : true
          minimum_coverage: 75
          report_name : Coverage_Report
