name: Remove Labels

on:
  pull_request:
    types: [synchronize]
    branches:
      - main
jobs:
  remove:
    name: Remove
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-remove-labels@v1
        name: Remove Publish Label
        with:
          labels: 'Publish'
